// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messaging.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Messaging {
  public static partial class Messenger
  {
    static readonly string __ServiceName = "messaging.Messenger";

    static readonly grpc::Marshaller<global::Messaging.MessageRequest> __Marshaller_messaging_MessageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messaging.MessageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Messaging.MessageResponse> __Marshaller_messaging_MessageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Messaging.MessageResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Messaging.MessageRequest, global::Messaging.MessageResponse> __Method_Message = new grpc::Method<global::Messaging.MessageRequest, global::Messaging.MessageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Message",
        __Marshaller_messaging_MessageRequest,
        __Marshaller_messaging_MessageResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Messaging.MessagingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Messenger</summary>
    public partial class MessengerClient : grpc::ClientBase<MessengerClient>
    {
      /// <summary>Creates a new client for Messenger</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MessengerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Messenger that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MessengerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MessengerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MessengerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Messaging.MessageResponse Message(global::Messaging.MessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Message(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Messaging.MessageResponse Message(global::Messaging.MessageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Message, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Messaging.MessageResponse> MessageAsync(global::Messaging.MessageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MessageAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Messaging.MessageResponse> MessageAsync(global::Messaging.MessageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Message, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MessengerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MessengerClient(configuration);
      }
    }

  }
}
#endregion
